# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-04 22:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('recommended_expenses_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('target_savings_budget_end', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('average_expenses_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('end_date_available_funds', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('end_date', models.DateField()),
                ('date_created', models.DateField(verbose_name=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('balance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='personal_finance.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('date', models.DateField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='personal_finance.Balance')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_finance.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('date', models.DateField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='personal_finance.Balance')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_finance.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('end_date', models.DateField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('balance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='personal_finance.Balance')),
            ],
        ),
    ]
