# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-10-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
