# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_account.Balance'),
        ),
        migrations.AddField(
            model_name='income',
            name='balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal_account.Balance'),
        ),
    ]
