# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-21 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_auto_20170519_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='total_expenses',
            new_name='total_expense',
        ),
    ]
