# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-23 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_auto_20170521_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
