# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0007_auto_20170526_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='personal_account.Balance'),
        ),
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='personal_account.Balance'),
        ),
    ]
