# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0008_auto_20170528_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(default=datetime.date(2017, 5, 28))),
                ('completed', models.BooleanField(default=False)),
                ('balance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='personal_account.Balance')),
            ],
        ),
    ]
