# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_savingsgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='end_date',
            field=models.DateField(),
        ),
    ]
