# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 22:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0011_savingsgoal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='recomended_expenses_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='balance',
            name='target_savings_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='balance',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
    ]
