# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-28 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0012_auto_20170528_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='target_savings_per_month',
            new_name='target_savings_month_end',
        ),
    ]
