# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-29 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0013_auto_20170528_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='recomended_expenses_per_day',
            new_name='recommended_expenses_per_day',
        ),
    ]
