# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-31 15:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0014_auto_20170529_1134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='balance',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
