# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-31 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0015_auto_20170531_1516'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
