# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-01 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0016_auto_20170531_1517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='balance',
            managers=[
            ],
        ),
    ]
