# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-03 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_account', '0017_auto_20170601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
