# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-04 17:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0018_balance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('end_date', models.DateField()),
                ('date_created', models.DateField(verbose_name=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='target_savings_month_end',
            new_name='average_expenses_per_day',
        ),
        migrations.AddField(
            model_name='balance',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='balance',
            name='end_date_available_funds',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='balance',
            name='target_savings_budget_end',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='personal_account.Balance'),
        ),
    ]
