# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0019_auto_20170604_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='end_date_available_funds',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
